# Generated by Django 4.2.2 on 2023-06-14 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre de ingrediente')),
            ],
            options={
                'verbose_name': 'Ingrediente',
                'verbose_name_plural': 'Ingredientes',
                'db_table': 'ingredientes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre de receta')),
                ('descripcion', models.CharField(max_length=250, verbose_name='Descripción')),
                ('preparacion', models.TextField(verbose_name='Modo de Preparación')),
                ('imagen', models.ImageField(upload_to='recetas')),
                ('ingredientes', models.ManyToManyField(to='recetas.ingrediente')),
            ],
            options={
                'verbose_name': 'Receta',
                'verbose_name_plural': 'Recetas',
                'db_table': 'recetas',
                'ordering': ['nombre'],
            },
        ),
    ]
