# Generated by Django 4.2.2 on 2023-06-20 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingrediente',
            name='imagen',
            field=models.ImageField(default=1, upload_to='ingredientes'),
            preserve_default=False,
        ),
    ]
