# Generated by Django 4.2.2 on 2023-06-22 21:04

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0002_ingrediente_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingrediente',
            name='imagen',
            field=models.ImageField(upload_to='ingredientes', verbose_name='Imagen del ingrediente'),
        ),
        migrations.AlterField(
            model_name='receta',
            name='descripcion',
            field=models.CharField(max_length=500, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='receta',
            name='preparacion',
            field=ckeditor.fields.RichTextField(verbose_name='Modo de Preparación'),
        ),
    ]
