# Generated by Django 4.2.2 on 2023-06-22 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0003_alter_ingrediente_imagen_alter_receta_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='imagen',
            field=models.ImageField(upload_to='recetas', verbose_name='Imagen'),
        ),
    ]
